name: frontend-deploy

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "**/*.ico"
      - "**/*.webmanifest"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  STORAGE_ACCOUNT: saswewtsz1

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: frontend-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sync entire site to $web (delete & replace)
        uses: azure/CLI@v2
        with:
          azcliversion: 2.62.0
          inlineScript: |
            set -euo pipefail
            ACCOUNT="${{ env.STORAGE_ACCOUNT }}"

            az storage blob sync \
              -c '$web' \
              -s . \
              --account-name "$ACCOUNT" \
              --delete-destination true \
              --exclude-path ".git;.github" \
              --exclude-pattern "*.md;*.MD;*.yml;*.yaml"
            
            echo "Website URL:"
            az storage account show -n "$ACCOUNT" --query "primaryEndpoints.web" -o tsv
